### ISSUE TITLE
Regarding readb and readw functionality

### ISSUE THREAD

**Issue by kalpesh12345-tech** [kelvinlawson/xmodem-1k#1]
Hi,
Can u please help with this api, which is part of inbyte and outbyte functionality
while (((c=readw(URX1)) & 0x2000) == 0) {

is readw corresponding to read word?
what does URX1 stand for? is it a buffer to receive data
any reason to do & 0x2000

It would be better if u can provide the function defination for readw, readb, writeb, writew

I am getting some undefined reference issue

**Comment by kelvinlawson** [comment]
Hi, this code was based on the following, you would be better asking there for help with this since it that is not part of the changes I made: https://www.menie.org/georges/embedded/xmodem.html
